# ====================================
# AnimalWhistle Plugin Configuration
# ====================================

# Item path
items:
  animal-whistle: "m.pets.animal_whistle"
  # Vanilla item example: "v.iron_ingot"
  # ItemsAdder item example: "ia.tfmc.animal_whistle"

# Feature settings
settings:
  detection-radius: 64.0    # Radius in blocks to detect animals
  glow-duration: 5          # Duration in seconds for the glowing effect
  whitelisted-animals:      # Entity types that will be highlighted
    - HORSE
    - DONKEY
    - MULE
    - LLAMA
    - TRADER_LLAMA

# Sound settings
sound:
  type: "ITEM_GOAT_HORN_SOUND_6"
  volume: 4.0               # 1 Volume = 16 blocks of range (in this case, 64 blocks)
  pitch: 2.0                # Range between 0.5 (half speed) and 2.0 (double speed)